vaadin:
  launch-browser: true

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/db
#    username: postgres
#    password: example
  servlet:
    multipart:
      max-file-size: 10MB
  threads:
    virtual:
      enabled: true
  application:
    name: vaadin-spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
#      api-key: not-needed
      chat:
        options:
          model: deepseek-v3.1:671b-cloud
      embedding:
        base-url: http://localhost:11434
        options:
          model: nomic-embed-text
#        api-key=not-needed

#    vectorstore:
#      pgvector:
#        initialize-schema: true
#        dimensions: 768

app:
  documentanalysis:
    maxFileSizeClientCheck: 10MB
  simplerag:
    maxFileSizeClientCheck: 10MB