vaadin:
  launch-browser: true

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: vaadin-spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
#      api-key: not-needed
      chat:
        options:
          model: deepseek-v3.1:671b-cloud
      embedding:
        base-url: http://localhost:11434
        options:
          model: nomic-embed-text
#        api-key=not-needed
